### ISSUE TITLE
Branches `start`, `chapter3`, `chapter4` do not exist. 

### ISSUE THREAD

**Issue by baibhavgautam** [react-in-action/letters-social#545]
I am reading through the book and noticed that branches `start`, `chapter3`, `chapter4` do not exist.

**Comment by markthethomas** [comment]
hey, sorry I missed this. An update for everyone: the book is currently in production, so we're finishing up final (as in _final_ 🎉) reviews — I'll these branches w/in the next week. Sorry for any confusion — we had to split chapters up and the branches had to get adjusted accordingly 🤔

**Comment by markthethomas** [comment]
Just an update: these branches should be available now!

**Comment by markthethomas** [comment]
Closing as these branches are now available
