### ISSUE TITLE
'build failed' with 'babel-preset-react-app' 

### ISSUE THREAD

**Issue by markthethomas** [react-in-action/letters-social#549]
cf. https://forums.manning.com/posts/list/0/42477.page#p123120

**Comment by ShelbyZ** [comment]
I think this breaks into smaller problems:

- Missing NODE_ENV=development for dev script
- Windows platforms don't understand NODE_ENV=* and would require SET NODE_ENV=*
- DisplayMap imported in Post.js is not used in Ch4 (not sure which chapter it is introduced)

**Comment by markthethomas** [comment]
Ah you know what, I think that development env is because I’ve had ‘development’ set as my default NODE_ENV for years and I just forgot it was set 😦

**Comment by ShelbyZ** [comment]
If you want to support multiple environments it may be worth looking into something like [cross-env](https://www.npmjs.com/package/cross-env) as I am not sure how to support both Windows & everything else in the same package.json.

**Comment by markthethomas** [comment]
@prusswan sorry about that - the chapters got split really late in the writing process (it was a massive headache to deal with, but it made sense). I can delete the old branches, but renaming the commit messages themselves wasn't something I didn't want to do w/ public branches (even during MEAP). I _could_ rebase and force push, but that can cause issues, too. is there a reason you've felt the need to use the commits in working with the code? As far as I can tell, there aren't any cases where you need to use the commits or messages when reading 👍

**Comment by markthethomas** [comment]
@ShelbyZ I do think cross-env may help here. It's worked well for me in the past, should be helpful here, too 👍

**Comment by prusswan** [comment]
@markthethomas I use the repository and commits to see if I missed anything going from chapter to chapter (like "diffs"), so if the numbers are inconsistent it is just harder to figure out. Maybe you can update the README to match the new chapters at least.

**Comment by markthethomas** [comment]
@prusswan make sense! Oh man, I can't believe those aren't updated - I totally missed that. I'll get those sorted ASAP 👍

**Comment by markthethomas** [comment]
@prusswan updated in latest 👍

**Comment by markthethomas** [comment]
This should be resolved on all branches

**Comment by markthethomas** [comment]
Hey sorry, will patch with cross-env as soon as I’m able 👍

**Comment by markthethomas** [comment]
Open to PRs though 😉
