### ISSUE TITLE
generateStaticMapImage in DisplayMap is using wrong url format for mapbox

### ISSUE THREAD

**Issue by prusswan** [react-in-action/letters-social#552]
In master/src/components/map/DisplayMap.js:

`https://api.mapbox.com/styles/v1/mapbox/streets-v10/static/${lat},${lng},12,0,0/600x175?access_token=${process.env.MAPBOX_API_TOKEN}`

should be

`https://api.mapbox.com/styles/v1/mapbox/streets-v10/static/${lng},${lat},12,0,0/600x175?access_token=${process.env.MAPBOX_API_TOKEN}`

**Comment by markthethomas** [comment]
@prusswan ah dang, need to get that fixed! If you're interested in contributing, feel free to open PRs to the relevant branches and we can get that resolved 👍
