### ISSUE TITLE
Build failed: 

### ISSUE THREAD

**Issue by ortemcheg** [react-in-action/letters-social#553]
Failed to install the dependencies for the app. Got this:

```
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tema/.npm/_logs/2018-07-25T13_25_04_593Z-debug.log
```

It looks like there's something wrong with node-sass. Any ideas how to fix this?
The OS is macOS 10.13.6; node v10.7.0; npm 6.0.1

Thanks.

**Comment by markthethomas** [comment]
hmmm I can take a look. Node-sass often has some issues; I'll try to reproduce, may be outdated packages

**Comment by ortemcheg** [comment]
Thanks a lot.
Looking forward to see your findings.

**Comment by markthethomas** [comment]
👍

**Comment by ortemcheg** [comment]
I cloned the repo and ran `npm install` again but got a whole host of new errors.
First it was the version of Python that failed. Had to downgrade from v. 3.5.4 to 2.7. Now it's `grpc@1.7.3~install: Failed to exec install script` And the log doesn't say anything about node-sass anymore.
Is there any other way to play with the code for Letters Social?
It's taken so much time and effort to get to chapter 4.3. that it feels so sad to be unable to continue :[

**Comment by ortemcheg** [comment]
Tried to install the app (Letter Social) on Linux (Ubuntu 16.04) and got the same error:
`Failed at the grpc@1.7.3 install script.`
It looks like it's the grpc@1.7.3. that needs to be fixed.
Any ideas how that could be done?

**Comment by prusswan** [comment]
How did you setup the node/npm environment? system node or nvm?

**Comment by markthethomas** [comment]
@ortemcheg can you downgrade your node to the support version? the carbon release line is what the project will support. I would imagine 10.x would work, but it's not a version I want to support till it goes LTS 👍 not sure why GRPC is in there, since this project wouldn't have used that for anything 🤔 let's try getting the node version to match first and see what that yields and work from there

**Comment by ortemcheg** [comment]
@markthethomas Downgrading worked! I set up the app successfully 🎉 Thank you very much! But when I tried to start the app (after generating sample data) it crashed 🤦🏼‍♂️ Shall I create a new issue for it or is it ok to continue here? 

@prusswan Thanks for helping me! It's system node on the mac and nvm on ubuntu

**Comment by markthethomas** [comment]
@ortemcheg ok cool - that's at least one step. What happens when you start the app? Can you post the stack here?

**Comment by prusswan** [comment]
Np, as @markthethomas said it is best to stick to `lts/carbon`. Also, you may need to reinstall the node_modules after changing the node version

**Comment by ortemcheg** [comment]
@markthethomas Sure.

[./src/index.js] ./src/index.js 1.78 kB {0} [built] [failed] [1 error]
    + 13 hidden modules

ERROR in ./src/index.js
Module build failed: Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing preset: "/Users/tema/coding/letters-social/node_modules/babel-preset-react-app/index.js")
    at Object.<anonymous> (/Users/tema/coding/letters-social/node_modules/babel-preset-react-app/index.js:47:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /Users/tema/coding/letters-social/node_modules/babel-core/lib/transformation/file/options/option-manager.js:296:17
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/tema/coding/letters-social/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/tema/coding/letters-social/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/tema/coding/letters-social/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/tema/coding/letters-social/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/tema/coding/letters-social/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/tema/coding/letters-social/node_modules/babel-core/lib/transformation/file/index.js:135:24)
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/index
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 5.03 kB {0} [built]
    [./node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Failed to compile

**Comment by prusswan** [comment]
Should be the same issue as #549. You can add `NODE_ENV=development` to the start of the "dev" command in package.json as suggested by ShelbyZ

**Comment by ortemcheg** [comment]
@prusswan Thanks a lot! Now the app is up and running.

@markthethomas Thank you again for your help!

**Comment by markthethomas** [comment]
@ortemcheg no problem! we'll get that NODE_ENV thing resolved soon too. Hope you enjoy the book and please feel free to reach out if you have any questions => https://twitter.com/MarkTheThomas
