### ISSUE TITLE
The start branch is missing

### ISSUE THREAD

**Issue by ortemcheg** [react-in-action/letters-social#556]
In the first lines of Chapter 4.3. (Starting to create Letter Social) we read: 

> “You should be on the start branch when starting out, but if you want to skip to the end of the chapter you can check out the chapter-4 branch”

But there is no ‘start’ branch in my repository. And if I switch to ‘chapter-4’ then (as promised) I’ll find  the code for the end of Chapter 4.

If we go back a few sections, here’s what we’ll find in 4.1.1. Getting the source code:

> ```
> git clone git@github.com:react-in-action/letters-social.git
> git checkout chapter-4
> ```
> That will clone the repository in the current directory and switch to the start branch (the starting branch for the project). 

Obviously that won’t.

So the question is: Where do I find the start branch?

Thanks

**Comment by markthethomas** [comment]
https://github.com/react-in-action/letters-social/tree/chapter-4, no?

**Comment by markthethomas** [comment]
Ah I see - I think this is some semantic confusion on my part due to the way the branches changed and editing. `chapter-4` is the "start" branch, I removed `start` somewhere in the process if I remember. sorry about that! that should go in errata for cleanup 👍
