### ISSUE TITLE
Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables

### ISSUE THREAD

**Issue by HaiderMalik12** [react-in-action/letters-social#557]
### Steps to reproduce the issue

1. Clone the repo
2. `git checkout chapter-4`
3. `npm install`
4. `npm run dev`

Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Validvalues are "development", "test", and "production". Instead, received: undefined. (While processing preset: "/Users/haidermalik504/Documents/React/code/letters-social/node_modules/babel-preset-react-app/index.js")

**Node version - v8.9.4**

Could you tell me how to resolve this issue?

**Comment by HaiderMalik12** [comment]
I resolved it by adding NODE_ENV=development
 "dev": "NODE_ENV=development npm-run-all -p api client:dev server:dev styles:w",

**Comment by markthethomas** [comment]
Hey, sorry for the trouble. I’ll be resolving that via a PR to all branches shortly here

**Comment by markthethomas** [comment]
_should_ be resolved on all branches now

**Comment by HaiderMalik12** [comment]
Thanks Mark!
