### ISSUE TITLE
SyntaxError: Unexpected token import, chapter-4

### ISSUE THREAD

**Issue by ortemcheg** [react-in-action/letters-social#558]
Looks like I got the same error as in #543 when I ran `npm run db:seed` in 'chapter-4' branch.
I added `transform-es2015-modules-commonjs` to the array of plugins in .babelrc which is in the project's root directory, but it didn't work. Maybe I should add that line to one of the other 11 .babelrc files that come with the project, but which one and how do I edit?

The error stack:
(node v.8.11.3, npm v.5.6.0, NODE_ENV=development)
`$ npm run db:seed`
 ```
letters-social@1.0.0 db:seed /Users/tema/coding/new_ltr/letters-social
 node -r @std/esm db/seed.js
/Users/tema/coding/new_ltr/letters-social/db/seed.js:1
(function(exports,require,module,__filename,__dirname){import { join } from 'path';
                                  ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at runInThisContext (vm.js:139:10)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! letters-social@1.0.0 db:seed: `node -r @std/esm db/seed.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the letters-social@1.0.0 db:seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tema/.npm/_logs/2018-08-01T08_03_20_403Z-debug.log
```

**Comment by markthethomas** [comment]
I’ll take a look! 👌

**Comment by ortemcheg** [comment]
@markthethomas Mark, thanks! I resolved it myself.

I edited .babelrc to add `transform-es2015-modules-commonjs` to the list of plugins but I didn't install the plugin itself. When I ran `npm run db:seed` babel didn't complain about the missing plugin, which made me think that the plugin was there but the solution simply didn't work.

To those who stumbled upon this issue:
1. Open .babelrc in the project's root directory
2. Add transform-es2015-modules-commonjs to the "plugins" array. After editing it should look like this: `"plugins": ["transform-class-properties", "transform-es2015-modules-commonjs"]`
3. Then run the following command in your terminal to install the plugin
`npm install --save-dev babel-plugin-transform-es2015-modules-commonjs`

**Comment by j-terranova** [comment]
I have made these changes and am still getting the issue. Error log below:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\jterr\\Documents\\NodeProjects\\Node\\node.exe',
1 verbose cli   'C:\\Users\\jterr\\Documents\\NodeProjects\\Node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'db:seed'
1 verbose cli ]
2 info using npm@6.13.6
3 info using node@v13.8.0
4 verbose run-script [ 'predb:seed', 'db:seed', 'postdb:seed' ]
5 info lifecycle letters-social@1.0.0~predb:seed: letters-social@1.0.0
6 info lifecycle letters-social@1.0.0~db:seed: letters-social@1.0.0
7 verbose lifecycle letters-social@1.0.0~db:seed: unsafe-perm in lifecycle true
8 verbose lifecycle letters-social@1.0.0~db:seed: PATH: C:\Users\jterr\Documents\NodeProjects\Node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\jterr\Documents\NodeProjects\letters-social-chapter-4\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\jterr\Documents\NodeProjects\GettingStarted\;C:\Users\jterr\Documents\NodeProjects\Node\;C:\Program Files\Git\cmd;C:\Program Files\OpenSSL-Win64\bin;C:\Users\jterr\.windows-build-tools\python27\;C:\Users\jterr\AppData\Local\Microsoft\WindowsApps;C:\Users\jterr\AppData\Roaming\npm;C:\Users\jterr\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\heroku\bin;
9 verbose lifecycle letters-social@1.0.0~db:seed: CWD: C:\Users\jterr\Documents\NodeProjects\letters-social-chapter-4
10 silly lifecycle letters-social@1.0.0~db:seed: Args: [ '/d /s /c', 'node -r @std/esm db/seed.js' ]
11 silly lifecycle letters-social@1.0.0~db:seed: Returned: code: 134  signal: null
12 info lifecycle letters-social@1.0.0~db:seed: Failed to exec db:seed script
13 verbose stack Error: letters-social@1.0.0 db:seed: `node -r @std/esm db/seed.js`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\jterr\Documents\NodeProjects\Node\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\jterr\Documents\NodeProjects\Node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid letters-social@1.0.0
15 verbose cwd C:\Users\jterr\Documents\NodeProjects\letters-social-chapter-4
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Users\\jterr\\Documents\\NodeProjects\\Node\\node.exe" "C:\\Users\\jterr\\Documents\\NodeProjects\\Node\\node_modules\\npm\\bin\\npm-cli.js" "run" "db:seed"
18 verbose node v13.8.0
19 verbose npm  v6.13.6
20 error code ELIFECYCLE
21 error errno 134
22 error letters-social@1.0.0 db:seed: `node -r @std/esm db/seed.js`
22 error Exit status 134
23 error Failed at the letters-social@1.0.0 db:seed script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
