### ISSUE TITLE
Fix only on master branch, not in other branch involved 

### ISSUE THREAD

**Issue by changyh** [react-in-action/letters-social#559]
The map error still not fixed on chapter-4.

ERROR in ./src/components/post/Post.js
Module not found: Error: Can't resolve '../map/DisplayMap' in '/home/pm/Books/ReactInAction/letters-social/src/components/post'
 @ ./src/components/post/Post.js 43:18-46
 @ ./src/app.js
 @ ./src/index.js

Please fix the error not only on master branch,...

**Comment by markthethomas** [comment]
Should be reflected now. Please open another issue if anything else comes up - thanks! :) 👍
