### ISSUE TITLE
How does the endpoint request in ch4: app.js work?

### ISSUE THREAD

**Issue by mbkupfer** [react-in-action/letters-social#579]
Hi @markthethomas 

I'm curious about the endpoint http request in chapter 4:

```javascript
endpoint: `${process.env
                .ENDPOINT}/posts?_page=1&_sort=date&_order=DESC&_embed=comments&_expand=user&_embed=likes`,
```

I don't understand how the results get paginated. I understand it has something to do with `_page=#`, but I don't see this in any specifications and furthermore, I don't understand how it knows to bring provide only 10 items. Could you please clarify?

Thanks!

**Comment by mbkupfer** [comment]
Never mind, I see now that this is part of JSON server documentation and that 10 is simply the default: https://github.com/typicode/json-server#paginate

**Comment by markthethomas** [comment]
@mbkupfer indeed! sorry I didn't get to answer this sooner but you're right - it's just part of the JSON-server API. It may have been safe to do, but I didn't want to add in server-side pagination etc. to the scope of the reader 😄
