### ISSUE TITLE
After clone a project can't get image source.

### ISSUE THREAD

**Issue by DuudeXX8** [react-in-action/letters-social#580]
Hi everyone.

I cloned  a project to my local machine and change branch to chapter-4. Install dependencies and after all of this I run npm run dev and get image error which says **net::ERR_BLOCKED_BY_CLIENT** (Image not found )

I don't change anything I just load project and install dependencies .
Here the sample of image component which show an image 

`<Ad
       url="https://ifelse.io/book"
       imageUrl="/static/assets/ads/ria.png"
/>`
`Ad` component only show's **ads by Letters**
Any idea?

Thanks in advance.

**Comment by mmraff** [comment]
Do you have an Ad blocker installed in your browser?
If so, try "Don't run on pages on this site" (that's the AdBlock-specific plugin option) or whatever the corresponding option in your blocker.

**Comment by DuudeXX8** [comment]
Yup, I have Ad blocker in browser. After change ad block configuration as you said it worked. Ty 👍
